apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      name: weather
      labels:
        app: weather
    spec:
      containers:
      - image: micgn/weather:v1.0
        name: weather
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /weather/status
#            port: 8080
#        readinessProbe:
#          httpGet:
#            path: /weather/status
#            port: 8080
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        env:
        - name: BASICAUTH_PW 
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: BASICAUTH_PW
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: MAIL_USER
        - name: MAIL_PW
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: MAIL_PW
        - name: MAIL_ALERT_MAIL
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: MAIL_ALERT_MAIL
        - name: BROKER_USER
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: BROKER_USER
        - name: BROKER_PW 
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: BROKER_PW
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: weather-data-pvc
